#Setting artifacts root directory and all the necessary directories
artifacts_root: artifacts

#Data ingestion repositories
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: ""
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Data Validation repositories
data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart_attack_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#Data Transformation repositories
data_transformation: 
  root_dir: artifacts/data_transformation
  processed_data_file: artifacts/data_transformation/processed_df.csv

