#Setting artifacts root directory and all the necessary directories
artifacts_root: artifacts

#Data ingestion repositories
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/samaTech-sys/Heart-Attack-Prediction-Model/raw/main/heart_attack_dataset.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Data Validation repositories
data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart_attack_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#Data processing Repositories 
data_processing:
  root_dir: artifacts/data_processing
  selected_data_file: artifacts/data_processing/selected_features.csv
  validation_report: artifacts/data_validation/selected_features_validation_report.txt

#Data Transformation repositories
data_transformation: 
  root_dir: artifacts/data_transformation
  processed_data_file: artifacts/data_transformation/processed_df.csv

#Data Splitting repositories
data_splitting: 
  root_dir: artifacts/data_splitting
  train_set_path: artifacts/data_splitting/train_set.csv
  test_set_path: artifacts/data_splitting/test_set.csv

#Data Transformation repositories
model_training: 
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_splitting/test_set.csv
  test_data_path: artifacts/data_splitting/train_set.csv
  model_name: model.joblib
 

#Data Evaluation repositories
model_evaluation: 
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_splitting/train_set.csv
  model_path: artifacts/model_training/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json